# Generated by Django 3.2.16 on 2023-07-09 13:52

import api.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0003_auto_20230702_1818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='name',
            field=models.CharField(help_text='Укажите имя ингредиента', max_length=32, unique=True, validators=[api.validators.validate_name], verbose_name='Имя ингредиента'),
        ),
    ]
