# Generated by Django 3.2.16 on 2023-07-13 13:21

import api.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0005_alter_ingredient_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='name',
            field=models.CharField(help_text='Укажите имя ингредиента', max_length=64, unique=True, validators=[api.validators.validate_name], verbose_name='Имя ингредиента'),
        ),
    ]
