version: '3'

volumes:
  pg_data:
  static:
  media:

services:
  db:
    image: postgres:13.10
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
    restart: always

  backend:
    image: puzzzo/foodgram_backend
    env_file: .env
    volumes:
      - static:/static/
      - media:/app/media/
    depends_on:
      - db
    restart: on-failure

  frontend:
    image: puzzzo/foodgram_frontend
    env_file: .env
    command: cp -r /app/build/. /static/
    volumes:
      - static:/static
    depends_on:
      - backend
    restart: no

  gateway:
    image: puzzzo/foodgram_gateway
    env_file: .env
    ports:
      - 9000:80
    volumes:
      - static:/static
      - media:/media
    depends_on:
      - backend
    restart: always
