# Generated by Django 3.2.16 on 2023-07-06 15:32

import api.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введите название тэга', max_length=32, unique=True, validators=[api.validators.validate_name], verbose_name='Название тэга')),
                ('slug', models.SlugField(help_text='Введите название слага', max_length=32, unique=True, verbose_name='Уникальный слаг')),
                ('color', models.CharField(default='#E26C2D', help_text='Введите например, #E26C2D', max_length=7, unique=True, validators=[django.core.validators.RegexValidator(message='Значение не цвет в формате HEX!', regex='^#([A-Fa-f0-9]{3,6})$')], verbose_name='Цвет')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
