# Generated by Django 3.2.16 on 2023-07-02 15:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='color',
            field=models.CharField(default='#E26C2D', help_text='Введите например, #E26C2D', max_length=7, unique=True, validators=[django.core.validators.RegexValidator(message='Значение не цвет в формате HEX!', regex='^#([A-Fa-f0-9]{3,6})$')], verbose_name='Цвет'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(help_text='Введите название тэга', max_length=32, unique=True, verbose_name='Название тэга'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='slug',
            field=models.SlugField(help_text='Введите название слага', max_length=32, unique=True, verbose_name='Уникальный слаг'),
        ),
    ]
