# Generated by Django 3.2.16 on 2023-07-05 15:40

import api.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0002_auto_20230702_1818'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='tag',
            name='unique_tags',
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(help_text='Введите название тэга', max_length=32, unique=True, validators=[api.validators.validate_name], verbose_name='Название тэга'),
        ),
    ]
