# Generated by Django 3.2.16 on 2023-07-15 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0002_alter_tag_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['name'], 'verbose_name': 'Таги', 'verbose_name_plural': 'Таги'},
        ),
    ]
