# Generated by Django 3.2.16 on 2023-07-03 14:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recipes', '0004_auto_20230702_1818'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='favorited_by',
            field=models.ManyToManyField(blank=True, related_name='favorites', to=settings.AUTH_USER_MODEL, verbose_name='Пользователи, добавившие в избранное'),
        ),
        migrations.DeleteModel(
            name='Favorite',
        ),
    ]
