# Generated by Django 3.2.16 on 2023-07-03 15:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recipes', '0005_auto_20230703_1708'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='shopping_cart',
            field=models.ManyToManyField(blank=True, related_name='shopping', to=settings.AUTH_USER_MODEL, verbose_name='Пользователи, добавившие в корзину'),
        ),
        migrations.DeleteModel(
            name='ShoppingCart',
        ),
    ]
