# Generated by Django 3.2.16 on 2023-07-13 13:16

import api.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_alter_recipeingredients_recipe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='name',
            field=models.CharField(help_text='Ведите название рецепта', max_length=48, validators=[api.validators.validate_name], verbose_name='Название рецепта'),
        ),
    ]
