# Generated by Django 3.2.16 on 2023-07-14 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0007_alter_recipe_name'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='favorite',
            name='unique_favorite_recipe',
        ),
        migrations.RemoveConstraint(
            model_name='recipeingredients',
            name='unique_ingredients_in_recipe',
        ),
        migrations.RemoveConstraint(
            model_name='shoppingcart',
            name='unique_shopping_recipe',
        ),
        migrations.AddConstraint(
            model_name='favorite',
            constraint=models.UniqueConstraint(fields=('user', 'recipe'), name='уникальность_рецепта_в_избранном'),
        ),
        migrations.AddConstraint(
            model_name='recipeingredients',
            constraint=models.UniqueConstraint(fields=('recipe', 'ingredient'), name='уникальность_ингредиента_в_рецепте'),
        ),
        migrations.AddConstraint(
            model_name='shoppingcart',
            constraint=models.UniqueConstraint(fields=('user', 'recipe'), name='уникальность_рецепта_в_корзине'),
        ),
    ]
