# Generated by Django 3.2.16 on 2023-07-14 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0008_auto_20230714_1123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.ImageField(help_text='Выберите фотографию рецепта', upload_to='recipes/', verbose_name='Фотография рецепта'),
        ),
    ]
